server:
  port: 8049
spring:
  application:
    name: maap
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    keyPrefix: qmkkan
    maxIdle: 3000
    max-total: 60000
    timeout: 6000ms
  jpa:
    show-sql: false
    database: MYSQL
    hibernate:
      ddl-auto: update
      event:
        merge:
          entity_copy_observer: allow
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  http:
    encoding:
      charset: utf-8
      enabled: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 50MB #最大请求文件的大小
      max-file-size: 50MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  pool:
    maxTotal: 153       #获取连接时的最大等待毫秒数100
    maxWaitMillis: 102

syslog:
  terminal: mq
reply:
  arti:
    capability: false
  auto:
    replyAll: true
dingtalk:
  mediaUploadUrl: https://oapi.dingtalk.com/media/upload

tokenUrl: http://124.42.103.210:8092/auth/token

maap:
  regionConfigMap:
    huadongnan:
      uploadUrl: http://161.189.118.121:7040/ultrafile
      downloadUrl: http://161.189.118.121:7040/zjdownload/
    huanan:
      uploadUrl: http://161.189.118.121:7040/gdfile/Content
      downloadUrl: http://161.189.118.121:7040/gddownload/
    huabei:
      uploadUrl: http://161.189.118.121:7040/huabeifile/Content
      downloadUrl: http://161.189.118.121:7040/huabeidownload/
    guanfangcsp:
      uploadUrl: http://161.189.118.121:7040/cspfile/Content
      downloadUrl: http://161.189.118.121:7040/cspdownload/
    guanfangcspjieru:
      uploadUrl: http://161.189.118.121:7040/cspaccessfile/Content
      downloadUrl: http://161.189.118.121:7040/cspaccessdownload/

npl:
  config:
    tokenUrl: http://60.247.77.151:46000/engine/serving/openapi/token/generate
    askUrl: http://60.247.77.151:46000/engine/serving/openapi/qa/v2/ask/GBBFL55NMY8W
    accessKeyId: 5e7f349aae3d42b19bf45a68f02510bf
    accessKeySecret: 4559e60e676241169827a8d12a32e047


