spring:
  datasource:
    url: jdbc:mysql://10.10.208.94:4100/msgcenter?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: admin
    password: Feinno@2019
  redis:
    host: 10.10.208.86
    port: 6379
fdfs:
  access:
    url: http://124.42.103.156:8089/
  tracker-list:            #TrackerList参数,支持多个
    - 10.10.208.115:22122
ffmpeg:
  path: /home/ffmpeg/bin/ffmpeg
  tmptath: /tmp/
  intelligencePath: /temp/intelligence/
rocketmq:
  name-server: 10.10.208.113:9876
  producer:
    group: group_http
  consumer:
    group: msg_sql_consumer
ruanwei:
  userid: 1193
  account: xmcx
  password: 123456
  sendUrl: http://123.57.213.247:5988/sms.aspx
  statusUrl: http://123.57.213.247:5988/statusApi.aspx
  msgUpUrl: http://123.57.213.247:5988/callApi.aspx

maap:
  config:
#    downloadMaapFileUrl: http://161.189.118.121:7040/maap/material/download
    envConfig: test

socketUrl: ws://124.42.103.210:8090/websocket?key=